[package]
name = "parser-test"
version = "0.1.0"
authors = ["Vincent Prouillet <balthek@gmail.com>"]
edition = "2018"

[dependencies]
logos = "0.12.0"
codespan-reporting = "0.11"
valuable =  { git = "https://github.com/tokio-rs/valuable/", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "parsing"
harness = false
