[package]
name = "parser-test"
version = "0.1.0"
authors = ["Vincent Prouillet <balthek@gmail.com>"]
edition = "2018"

[dependencies]
logos = "0.12.0"
codespan-reporting = "0.11"

[[bin]]
name = "testing"
path = "src/testing.rs"
